# Generated by Django 2.1.2 on 2018-10-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accapp', '0002_profilemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
