# Generated by Django 2.1.2 on 2018-10-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accapp', '0004_auto_20181015_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
