# Generated by Django 2.1.2 on 2018-10-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_description',
            new_name='cat_des',
        ),
    ]
